apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SpringDaylight/Bolrea-Malrea-Gitops.git
    targetRevision: dev
    path: overlays/dev/backend

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true