apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-jwt-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: JWT_SECRET
    remoteRef:
      key: movie-dev/jwt-secret
      property: JWT_SECRET
